package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.matrix
import jetbrains.buildServer.configs.kotlin.triggers.retryBuild
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    vcs {

        check(branchFilter == "+pr:blabla") {
            "Unexpected option value: branchFilter = $branchFilter"
        }
        branchFilter = """
            +:production
            +:<default>
        """.trimIndent()
    }

    triggers {
        add {
            retryBuild {
                delaySeconds = 15
            }
        }
    }

    features {
        add {
            matrix {
                os = listOf(
                    value("Linux"),
                    value("Mac OS")
                )
            }
        }
    }
}
